In [1]:
import pandas as pd
from numpy.matlib import empty

## Question 1

In [2]:
print(pd.__version__)

3.0.6

## Question 2

In [3]:
data = pd.read_csv(r'/home/vitali/PycharmProjects/MLZoomcamp2026/car_fuel_efficiency_2026.csv')
print(f"Number of rows: {data.shape[0]}")

Number of rows: 10000

## Question 3

In [4]:
fuel_type_info = data["fuel_type"].value_counts()
print(fuel_type_info)

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [5]:
print(f"Count of fuel types: {len(fuel_type_info)}")

Count of fuel types: 3

## Question 4

In [6]:
empty_cols = data.columns[data.eq("").any()].to_list()
print(empty_cols)

[]

In [7]:
col_has_miss_val = data.columns[data.isnull().any()].to_list()
print(col_has_miss_val)

['horsepower', 'acceleration']

In [8]:
print(f"Number of columns with missing values: {len(col_has_miss_val)}")

Number of columns with missing values: 2

## Question 5

In [9]:
fuel_eff_frame = data['fuel_efficiency_mpg']
print(f"Max value: {fuel_eff_frame.max()}")

Max value: 41.2

## Qeustion 6

In [10]:
horsepower_frame = data['horsepower']
median_horsepower = horsepower_frame.median()
print(f"Median horsepower: {median_horsepower}")

Median horsepower: 254.0

In [11]:
horsepower_frame.value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [12]:
most_freq = horsepower_frame.value_counts().index[0]
print(f"Most frequent horsepower: {most_freq}")

Most frequent horsepower: 252.0

In [13]:
horsepower_fill_frame = horsepower_frame.fillna(most_freq)
median_fill_horsepower = horsepower_fill_frame.median()
print(f"Median horsepower after filling: {median_fill_horsepower}")

Median horsepower after filling: 252.0

In [14]:
print('Median value has decreased: ' + str(median_horsepower > median_fill_horsepower))

Median value has decreased: True

## Question 7

In [15]:
data.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [16]:
data_car_asia = data[data.origin == "Asia"]
data_car_asia = data_car_asia[['vehicle_weight', 'model_year']][0:7]
data_car_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [17]:
import numpy as np

In [18]:
x = data_car_asia.values
XTX = x.T.dot(x)
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = np.linalg.inv(XTX).dot(x.T).dot(y)
print(w)
print(f"Sum of weights: {np.sum(w).round(3)}")

[0.13644777 0.2327492 ]
Sum of weights: 0.369